
cc_binary(
    name = 'server',
    srcs = [
        'server.cpp', 
    ],
    incs = [
    ],
    deps = [
        '//src/extension/zookeeper/:pebble_zookeeper',
        '//src/server/:pebble_server',
    ],
)

