
cc_library(
    name = 'pebble_common',
    srcs = [
        'base64.cpp',
        'condition_variable.cpp',
        'coroutine.cpp',
        'cpu.cpp',
		'db_list.cpp',
        'dir_util.cpp',
        'error.cpp',
        'file_util.cpp',
        'ini_reader.cpp',
        'kv_cache.cpp',
        'log.cpp',
        'memory.cpp',
        'net_util.cpp',
        'sha1.cpp',
        'string_utility.cpp',
        'thread.cpp',
        'thread_pool.cpp',
        'timer.cpp',
        'time_utility.cpp',
        'random.cpp',
    ],
    extra_cppflags = [
        '--std=c++0x',
    ],
    incs = [
    ],
    deps = [
    ],
)
